### PR TITLE
Add tests for the visualization

### PR DESCRIPTION
**Pull request by billwan96**
For that I have change the seaborn plots to altair plot so that it is easier to test

### CODE REVIEW

**Review by czwcandy — CHANGES_REQUESTED** [review]
Hi Bill, 
Thank you for your contribution for testing visualization. Could you please make some changes on your file? Please delete all the code which is not needed here in your function, especially the correlation function. Also, can you change your file name corresponding to the function name. Please follow the the Tiffany's example as reference. https://github.com/ttimbers/demo-tests-ds-analysis-python. I hope it can help.

**Comment by billwan96** [comment]
hopefully it should be fine now lol. But let me know if there should be any further changes

**Review by tangyl92 — CHANGES_REQUESTED** [review]
pls add a docstring in function

**Comment by billwan96** [comment]
done

**Review by tangyl92 — APPROVED** [review]

**Review by tangyl92 — APPROVED** [review]

**Review by czwcandy — APPROVED** [review]

**Pull request merged**
